#!/bin/sh

set -e # Exit on any failure

cp .bash_profile      $HOME/.bash_profile
cp .gitconfig         $HOME/.gitconfig
cp .gitignore_global  $HOME/.gitignore_global
cp .irbrc             $HOME/.irbrc
cp .rspec             $HOME/.rspec
cp .inputrc           $HOME/.inputrc

echo "Dotfiles in $USER's home directory have been replaced"
echo "Reload shell for changes to take effect"
echo "Please set your git user name and email again."
